# -*- coding: utf-8 -*-
"""demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1uoUtF4NOaz4Ko5D3wCX7IdM3x0DXqk
"""

# demo.py
import os
import sys
import math
import ollama

# Point the Python client to the Docker Ollama server
# (default is http://127.0.0.1:11434, so this is optional)
ollama_client = ollama.Client(host='http://127.0.0.1:11434')

EMBEDDING_MODEL = 'hf.co/CompendiumLabs/bge-base-en-v1.5-gguf'
LANGUAGE_MODEL  = 'hf.co/bartowski/Llama-3.2-1B-Instruct-GGUF'

# ---------- Load dataset ----------
dataset_path = 'cat-facts.txt'
if not os.path.exists(dataset_path):
    print(f'Error: {dataset_path} not found. Create it in this folder (one fact per line).')
    sys.exit(1)

with open(dataset_path, 'r', encoding='utf-8') as f:
    dataset = [line.strip() for line in f if line.strip()]
print(f'Loaded {len(dataset)} entries')

# ---------- Build a tiny "vector DB" in memory ----------
# Each entry is (text_chunk, embedding_vector)
VECTOR_DB = []

def embed_text(text: str):
    resp = ollama_client.embed(model=EMBEDDING_MODEL, input=text)
    # Newer ollama returns {'embeddings': [[...]]}; older returns shape slightly different.
    vec = resp['embeddings'][0] if isinstance(resp['embeddings'][0], list) else resp['embeddings']
    return vec

def add_chunk_to_database(chunk: str):
    vec = embed_text(chunk)
    VECTOR_DB.append((chunk, vec))

print('Indexing chunks...')
for i, chunk in enumerate(dataset, start=1):
    add_chunk_to_database(chunk)
    if i % 5 == 0 or i == len(dataset):
        print(f'  added {i}/{len(dataset)}')

# ---------- Retrieval (cosine similarity) ----------
def cosine_similarity(a, b):
    dot = sum(x*y for x, y in zip(a, b))
    na  = math.sqrt(sum(x*x for x in a))
    nb  = math.sqrt(sum(x*x for x in b))
    return dot / (na * nb + 1e-12)

def retrieve(query: str, top_n=3):
    qvec = embed_text(query)
    sims = []
    for chunk, vec in VECTOR_DB:
        sims.append((chunk, cosine_similarity(qvec, vec)))
    sims.sort(key=lambda x: x[1], reverse=True)
    return sims[:top_n]

def retrieve_and_format(query, top_n=3):
    """
    Calls `retrieve(query, top_n)` to get a list of (chunk, score) pairs
    and returns a single nicely formatted string.
    """
    results = retrieve(query, top_n=top_n)   # [(chunk:str, score:float), ...]
    if not results:
        return "No results found."

    lines = []
    for i, (chunk, score) in enumerate(results, start=1):
        # clean trailing newlines/spaces from the chunk for pretty printing
        clean = chunk.strip()
        lines.append(f'Rank {i} ({score:.2f}): "{clean}"')
    return "\n".join(lines)

# ---------- Simple RAG generation ----------
def rag_answer(question: str, top_k=3):
    hits = retrieve(question, top_n=top_k)
    print('\nRetrieved knowledge:')
    for chunk, s in hits:
        print(f' - (sim={s:.2f}) {chunk}')

    context = '\n'.join(f' - {c}' for c, _ in hits)
    system_prompt = (
        "You are a helpful assistant.\n"
        "Use only the following pieces of context to answer the user's question.\n"
        "If the answer is not in the context, say you don't know.\n"
        f"{context}"
    )

    stream = ollama_client.chat(
        model=LANGUAGE_MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": question},
        ],
        stream=True,
    )

    print('\nChatbot response:')
    full = []
    for chunk in stream:
        token = chunk['message']['content']
        full.append(token)
        print(token, end='', flush=True)
    print()
    return ''.join(full)

if __name__ == '__main__':
    try:
        q = input('Ask me a question: ')
    except KeyboardInterrupt:
        print('\nBye')
        sys.exit(0)
    rag_answer(q, top_k=3)


if __name__ == '__main__':
    question = input('Enter a question: ')
    formatted_output = retrieve_and_format(question, top_n=5)
    print('\nTop 5 relevant chunks:\n')
    print(formatted_output)