# -*- coding: utf-8 -*-
"""Daily Challenge: Build Your First AI Greeter: Daily Greeter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kenSO56wDGf8pYQ5FLNbirjP5tVXVl0S
"""

# daily_greeter.py

from datetime import datetime
import gradio as gr


def get_time_of_day():
    """
    Figure out if it's morning, afternoon or evening
    based on the current hour on your machine.
    """
    hour = datetime.now().hour

    if 5 <= hour < 12:
        return "morning"
    elif 12 <= hour < 18:
        return "afternoon"
    else:
        return "evening"


def greet(name: str, language: str) -> str:
    """
    Takes a name + language and returns a greeting
    that depends on the time of day.
    """

    # Handle empty name nicely
    name = name.strip()
    if not name:
        name = "there"

    time_of_day = get_time_of_day()

    if language == "English":
        if time_of_day == "morning":
            return f"Good morning, {name}! 🌅"
        elif time_of_day == "afternoon":
            return f"Good afternoon, {name}! 🌞"
        else:
            return f"Good evening, {name}! 🌙"

    elif language == "French":
        if time_of_day == "morning":
            return f"Bonjour, {name} ! 🌅"
        elif time_of_day == "afternoon":
            return f"Bon après-midi, {name} ! 🌞"
        else:
            return f"Bonsoir, {name} ! 🌙"

    # Fallback (shouldn't really happen with our dropdown)
    return f"Hello, {name}!"


# ----- Gradio Interface -----

demo = gr.Interface(
    fn=greet,  # the Python function we just wrote
    inputs=[
        gr.Textbox(label="Your name", placeholder="Enter your name here"),
        gr.Dropdown(
            choices=["English", "French"],
            value="English",
            label="Greeting language",
        ),
    ],
    outputs=gr.Textbox(label="Greeting"),
    title="Mini Greeter App",
    description="I greet you by name and time of day 😊",
    examples=[
        ["Alice", "English"],
        ["Jean", "French"],
    ],
)

if __name__ == "__main__":
    demo.launch()