# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srzfh0LfahDIHr7KylGWDfiYXithMawZ
"""

# app.py
import streamlit as st
# 👇 MUST be the first Streamlit call in the file
st.set_page_config(page_title="Sentiment + RAG Response", page_icon="💬", layout="centered")

import time
from pathlib import Path
import os
import numpy as np
import faiss
import torch
from sentence_transformers import SentenceTransformer
from transformers import pipeline
from gen_infer import generate_response

# ---------- Paths ----------
HERE = Path(__file__).resolve().parent if "__file__" in globals() else Path.cwd()
INDEX_PATH = HERE / "rag_index.faiss"
DOC_PATH   = HERE / "rag_text.npy"

# ---------- Cached bootstrap (loads once) ----------
@st.cache_resource(show_spinner=True)
def bootstrap():
    # 1) FAISS index
    assert INDEX_PATH.exists(), f"Index file not found at: {INDEX_PATH}"
    index = faiss.read_index(str(INDEX_PATH))

    # 2) Document store
    assert DOC_PATH.exists(), f"Document store not found at: {DOC_PATH}"
    doc_store = np.load(str(DOC_PATH), allow_pickle=True).tolist()

    # 3) Embeddings model (avoid meta-tensor issue by setting device)
    device_str = "cuda" if torch.cuda.is_available() else "cpu"
    embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", device=device_str)

    # 4) Sentiment pipeline (GPU if available, else CPU)
    device = 0 if torch.cuda.is_available() else -1
    clf = pipeline(
        "sentiment-analysis",
        model="distilbert-base-uncased-finetuned-sst-2-english",
        device=device
    )
    return index, doc_store, embedder, clf

index, doc_store, embedder, clf = bootstrap()

# ---------- Helpers ----------
def retrieve_topk(query: str, k: int = 3):
    if k <= 0:
        return []
    qv = embedder.encode([query], normalize_embeddings=True)
    D, I = index.search(qv.astype("float32"), k)
    return [doc_store[i] for i in I[0]]

def predict_sentiment(text: str):
    out = clf(text)[0]
    return out["label"], float(out["score"])

# ---------- UI ----------
st.title("💬 Sentiment + Context-Aware Reply")

user_text = st.text_area(
    "Enter tweet/text",
    height=120,
    placeholder="e.g., The update fixed my issue. Nice work!"
)
k = st.slider("Top-K retrieved docs", 0, 5, 3)
temp = st.slider("Creativity (temperature)", 0.0, 1.5, 0.3, 0.1)

if st.button("Generate"):
    if not user_text.strip():
        st.warning("Please enter some text.")
        st.stop()

    t0 = time.time()
    label, conf = predict_sentiment(user_text)
    retrieved = retrieve_topk(user_text, k=k)
    reply = generate_response(user_text, retrieved, label, temperature=temp)
    dt = (time.time() - t0) * 1000

    st.subheader("Result")
    st.write(f"**Sentiment:** `{label}` (conf {conf:.2f})")

    if retrieved:
        with st.expander("Retrieved context"):
            for i, d in enumerate(retrieved, 1):
                st.write(f"**{i}.** {d[:500]}")

    st.write("**Reply:**")
    st.success(reply)
    st.caption(f"Latency: {dt:.0f} ms")

    # Simple thumbs feedback
    col1, col2 = st.columns(2)
    with col1:
        good = st.button("👍 Helpful")
    with col2:
        bad = st.button("👎 Not helpful")

    if good or bad:
        import csv
        os.makedirs("feedback", exist_ok=True)
        with open("feedback/ratings.csv", "a", newline="", encoding="utf-8") as f:
            csv.writer(f).writerow([
                user_text, label, conf, " | ".join(retrieved), reply,
                "up" if good else "down"
            ])
        st.toast("Feedback recorded. Thanks!", icon="✅")

