# -*- coding: utf-8 -*-
"""gen_infer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pxggp6R_fmREC_mvrTHJu6S-movTZnpT
"""

# gen_infer.py
from transformers import pipeline

# You can replace this with a fine-tuned or custom model later
generator = pipeline("text-generation", model="gpt2")

def generate_response(user_text, retrieved_docs=None, sentiment_label=None, temperature=0.7):
    """
    Generates a context-aware response using retrieved documents and sentiment.
    """
    # Build a simple prompt for the generator
    context = ""
    if retrieved_docs:
        context = " ".join(retrieved_docs[:2])  # take top 2 docs only for brevity

    prompt = f"""
    The following text expresses a {sentiment_label.lower()} sentiment.
    User said: "{user_text}"
    Based on the context: "{context}"
    Write a short, thoughtful response that matches the sentiment.
    """

    # Generate response
    response = generator(
        prompt,
        max_length=100,
        num_return_sequences=1,
        temperature=temperature,
        pad_token_id=50256  # avoid warning for GPT-2
    )[0]["generated_text"]

    # Return the generated response cleanly
    return response.strip()