# -*- coding: utf-8 -*-
"""exercise1_gradio_toolkit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwnZwLnRSjgIvawNLaRuy0MOLmD6bYwn

# **Exercise 1 – Gradio Multi-Function Toolkit**
"""

import gradio as gr

# ---- 1) Backend logic function ----
def multi_tool(tool_choice, user_input):
    """
    tool_choice: one of "Greet", "Echo", "Square a Number"
    user_input: string from the textbox
    """
    if tool_choice == "Greet":
        # e.g. input: "Tobi" -> "Hello, Tobi!"
        return f"Hello, {user_input}!"

    elif tool_choice == "Echo":
        # e.g. input: "I love AI" -> "You said: I love AI"
        return f"You said: {user_input}"

    elif tool_choice == "Square a Number":
        # e.g. input: "5" -> 25
        try:
            num = float(user_input)
            squared = num ** 2
            return f"The square of {num} is {squared}"
        except ValueError:
            return "❗ Please enter a valid number, like 4 or 3.5."

    else:
        return "Unknown option."


# ---- 2) Build the Interface UI ----

# Dropdown for tool selection
tool_dropdown = gr.Dropdown(
    choices=["Greet", "Echo", "Square a Number"],
    value="Greet",
    label="Choose a tool"
)

# Textbox for the input value (we’ll parse as number when needed)
value_box = gr.Textbox(
    label="Enter text or number",
    placeholder="Type a name, a sentence, or a number"
)

# Single text output
output_box = gr.Textbox(
    label="Result"
)

# Gradio Interface tying UI ↔ function together
demo = gr.Interface(
    fn=multi_tool,                         # backend function
    inputs=[tool_dropdown, value_box],     # what the user provides
    outputs=output_box,                    # what we show back
    title="🧰 Multi-Function Toolkit",
    description=(
        "Choose a tool: Greet someone, Echo your text, "
        "or Square a Number."
    ),
    examples=[
        ["Greet", "Tobi"],
        ["Echo", "I am learning LLMs"],
        ["Square a Number", "5"]
    ]
)

# ---- 3) Launch the app ----
if __name__ == "__main__":
    demo.launch()

"""# **EXERCISE 2 — Gradio Blocks Two-Step Calculator**"""

import gradio as gr

# ---- Backend calculator logic ----
def calculate(n1, n2, op):
    if op == "Add":
        return n1 + n2
    elif op == "Multiply":
        return n1 * n2
    else:
        return "Invalid operation."

# ---- Build UI with Blocks ----
with gr.Blocks() as demo:
    gr.Markdown("## ➗ Simple Two-Step Calculator")

    with gr.Row():
        num1 = gr.Number(label="Number 1")
        num2 = gr.Number(label="Number 2")

    op = gr.Radio(choices=["Add", "Multiply"], label="Operation")

    btn = gr.Button("Calculate")
    result = gr.Label(label="Result")

    btn.click(fn=calculate, inputs=[num1, num2, op], outputs=result)

if __name__ == "__main__":
    demo.launch()

"""# **EXERCISE 3 — Streamlit Stateful Chatbot**"""

import streamlit as st

st.title("💬 Stateful Memory Chatbot")

# Initialize session history
if "chat_history" not in st.session_state:
    st.session_state["chat_history"] = []

# Display previous messages
for role, msg in st.session_state["chat_history"]:
    with st.chat_message(role):
        st.write(msg)

# Input box
user_msg = st.chat_input("Say something...")

if user_msg:
    # Save user message
    st.session_state["chat_history"].append(("user", user_msg))

    # Simple bot reply (echo)
    bot_reply = f"You said: {user_msg}"
    st.session_state["chat_history"].append(("assistant", bot_reply))

    # Display bot reply live
    with st.chat_message("assistant"):
        st.write(bot_reply)

# Clear button
if st.button("Clear Chat"):
    st.session_state["chat_history"] = []
    st.experimental_rerun()

"""# **EXERCISE 4 — Streamlit Dynamic Mini Dashboard**"""

import streamlit as st
import numpy as np
import pandas as pd

st.title("📊 Dynamic Mini Dashboard")

# 1) Random line chart
data = np.random.randn(20, 3)
st.line_chart(data)

# 2) Selector
choice = st.radio("Choose a view:", ["Show Code", "Show JSON"])

# 3) Conditional display
if choice == "Show Code":
    st.code("""
def hello():
    print("Hello, world!")
hello()
""")
else:
    st.json({
        "name": "Tobi",
        "role": "AI Builder",
        "skills": ["Python", "LLMs", "UX", "Vision AI"]
    })

# Bonus: Display an image
st.image("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Artificial_Intelligence_logo_notext.svg/256px-Artificial_Intelligence_logo_notext.svg.png")

"""# **EXERCISE 5 — FastAPI Smart Responder**"""

from fastapi import FastAPI
from pydantic import BaseModel
import uvicorn

app = FastAPI()

class Query(BaseModel):
    message: str

@app.post("/respond")
def respond(q: Query):
    msg = q.message.lower()

    if "math" in msg:
        return {"reply": "Using calculator tool..."}

    if "date" in msg:
        return {"reply": "Fetching current date..."}

    return {"reply": "Default LLM response."}

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)